# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'designerdTXqUf.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################
from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.b_Start = QPushButton(self.centralwidget)
        self.b_Start.setObjectName(u"b_Start")
        self.b_Start.setGeometry(QRect(30, 480, 91, 41))
        self.b_Exit = QPushButton(self.centralwidget)
        self.b_Exit.setObjectName(u"b_Exit")
        self.b_Exit.setGeometry(QRect(670, 480, 91, 41))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 30, 121, 41))
        self.in_Name = QTextEdit(self.centralwidget)
        self.in_Name.setObjectName(u"in_Name")
        self.in_Name.setGeometry(QRect(30, 70, 91, 41))
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(220, 80, 31, 31))
        self.textEdit_2 = QTextEdit(self.centralwidget)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(280, 80, 31, 31))
        self.textEdit_3 = QTextEdit(self.centralwidget)
        self.textEdit_3.setObjectName(u"textEdit_3")
        self.textEdit_3.setGeometry(QRect(280, 110, 31, 31))
        self.textEdit_4 = QTextEdit(self.centralwidget)
        self.textEdit_4.setObjectName(u"textEdit_4")
        self.textEdit_4.setGeometry(QRect(250, 110, 31, 31))
        self.textEdit_5 = QTextEdit(self.centralwidget)
        self.textEdit_5.setObjectName(u"textEdit_5")
        self.textEdit_5.setGeometry(QRect(220, 110, 31, 31))
        self.textEdit_6 = QTextEdit(self.centralwidget)
        self.textEdit_6.setObjectName(u"textEdit_6")
        self.textEdit_6.setGeometry(QRect(310, 80, 31, 31))
        self.textEdit_1 = QTextEdit(self.centralwidget)
        self.textEdit_1.setObjectName(u"textEdit_1")
        self.textEdit_1.setGeometry(QRect(250, 80, 31, 31))
        self.textEdit_8 = QTextEdit(self.centralwidget)
        self.textEdit_8.setObjectName(u"textEdit_8")
        self.textEdit_8.setGeometry(QRect(310, 110, 31, 31))
        self.textEdit_9 = QTextEdit(self.centralwidget)
        self.textEdit_9.setObjectName(u"textEdit_9")
        self.textEdit_9.setGeometry(QRect(280, 170, 31, 31))
        self.textEdit_10 = QTextEdit(self.centralwidget)
        self.textEdit_10.setObjectName(u"textEdit_10")
        self.textEdit_10.setGeometry(QRect(220, 140, 31, 31))
        self.textEdit_11 = QTextEdit(self.centralwidget)
        self.textEdit_11.setObjectName(u"textEdit_11")
        self.textEdit_11.setGeometry(QRect(280, 140, 31, 31))
        self.textEdit_12 = QTextEdit(self.centralwidget)
        self.textEdit_12.setObjectName(u"textEdit_12")
        self.textEdit_12.setGeometry(QRect(220, 170, 31, 31))
        self.textEdit_13 = QTextEdit(self.centralwidget)
        self.textEdit_13.setObjectName(u"textEdit_13")
        self.textEdit_13.setGeometry(QRect(310, 140, 31, 31))
        self.textEdit_14 = QTextEdit(self.centralwidget)
        self.textEdit_14.setObjectName(u"textEdit_14")
        self.textEdit_14.setGeometry(QRect(250, 140, 31, 31))
        self.textEdit_15 = QTextEdit(self.centralwidget)
        self.textEdit_15.setObjectName(u"textEdit_15")
        self.textEdit_15.setGeometry(QRect(250, 170, 31, 31))
        self.textEdit_16 = QTextEdit(self.centralwidget)
        self.textEdit_16.setObjectName(u"textEdit_16")
        self.textEdit_16.setGeometry(QRect(310, 170, 31, 31))
        self.textEdit_17 = QTextEdit(self.centralwidget)
        self.textEdit_17.setObjectName(u"textEdit_17")
        self.textEdit_17.setGeometry(QRect(400, 110, 31, 31))
        self.textEdit_18 = QTextEdit(self.centralwidget)
        self.textEdit_18.setObjectName(u"textEdit_18")
        self.textEdit_18.setGeometry(QRect(340, 80, 31, 31))
        self.textEdit_19 = QTextEdit(self.centralwidget)
        self.textEdit_19.setObjectName(u"textEdit_19")
        self.textEdit_19.setGeometry(QRect(400, 80, 31, 31))
        self.textEdit_20 = QTextEdit(self.centralwidget)
        self.textEdit_20.setObjectName(u"textEdit_20")
        self.textEdit_20.setGeometry(QRect(340, 110, 31, 31))
        self.textEdit_21 = QTextEdit(self.centralwidget)
        self.textEdit_21.setObjectName(u"textEdit_21")
        self.textEdit_21.setGeometry(QRect(430, 80, 31, 31))
        self.textEdit_22 = QTextEdit(self.centralwidget)
        self.textEdit_22.setObjectName(u"textEdit_22")
        self.textEdit_22.setGeometry(QRect(370, 80, 31, 31))
        self.textEdit_23 = QTextEdit(self.centralwidget)
        self.textEdit_23.setObjectName(u"textEdit_23")
        self.textEdit_23.setGeometry(QRect(370, 110, 31, 31))
        self.textEdit_24 = QTextEdit(self.centralwidget)
        self.textEdit_24.setObjectName(u"textEdit_24")
        self.textEdit_24.setGeometry(QRect(430, 110, 31, 31))
        self.textEdit_25 = QTextEdit(self.centralwidget)
        self.textEdit_25.setObjectName(u"textEdit_25")
        self.textEdit_25.setGeometry(QRect(400, 170, 31, 31))
        self.textEdit_26 = QTextEdit(self.centralwidget)
        self.textEdit_26.setObjectName(u"textEdit_26")
        self.textEdit_26.setGeometry(QRect(340, 140, 31, 31))
        self.textEdit_27 = QTextEdit(self.centralwidget)
        self.textEdit_27.setObjectName(u"textEdit_27")
        self.textEdit_27.setGeometry(QRect(400, 140, 31, 31))
        self.textEdit_28 = QTextEdit(self.centralwidget)
        self.textEdit_28.setObjectName(u"textEdit_28")
        self.textEdit_28.setGeometry(QRect(340, 170, 31, 31))
        self.textEdit_29 = QTextEdit(self.centralwidget)
        self.textEdit_29.setObjectName(u"textEdit_29")
        self.textEdit_29.setGeometry(QRect(430, 140, 31, 31))
        self.textEdit_30 = QTextEdit(self.centralwidget)
        self.textEdit_30.setObjectName(u"textEdit_30")
        self.textEdit_30.setGeometry(QRect(370, 140, 31, 31))
        self.textEdit_31 = QTextEdit(self.centralwidget)
        self.textEdit_31.setObjectName(u"textEdit_31")
        self.textEdit_31.setGeometry(QRect(370, 170, 31, 31))
        self.textEdit_32 = QTextEdit(self.centralwidget)
        self.textEdit_32.setObjectName(u"textEdit_32")
        self.textEdit_32.setGeometry(QRect(430, 170, 31, 31))
        self.textEdit_33 = QTextEdit(self.centralwidget)
        self.textEdit_33.setObjectName(u"textEdit_33")
        self.textEdit_33.setGeometry(QRect(520, 110, 31, 31))
        self.textEdit_34 = QTextEdit(self.centralwidget)
        self.textEdit_34.setObjectName(u"textEdit_34")
        self.textEdit_34.setGeometry(QRect(460, 80, 31, 31))
        self.textEdit_35 = QTextEdit(self.centralwidget)
        self.textEdit_35.setObjectName(u"textEdit_35")
        self.textEdit_35.setGeometry(QRect(520, 80, 31, 31))
        self.textEdit_36 = QTextEdit(self.centralwidget)
        self.textEdit_36.setObjectName(u"textEdit_36")
        self.textEdit_36.setGeometry(QRect(460, 110, 31, 31))
        self.textEdit_37 = QTextEdit(self.centralwidget)
        self.textEdit_37.setObjectName(u"textEdit_37")
        self.textEdit_37.setGeometry(QRect(550, 80, 31, 31))
        self.textEdit_38 = QTextEdit(self.centralwidget)
        self.textEdit_38.setObjectName(u"textEdit_38")
        self.textEdit_38.setGeometry(QRect(490, 80, 31, 31))
        self.textEdit_39 = QTextEdit(self.centralwidget)
        self.textEdit_39.setObjectName(u"textEdit_39")
        self.textEdit_39.setGeometry(QRect(490, 110, 31, 31))
        self.textEdit_40 = QTextEdit(self.centralwidget)
        self.textEdit_40.setObjectName(u"textEdit_40")
        self.textEdit_40.setGeometry(QRect(550, 110, 31, 31))
        self.textEdit_41 = QTextEdit(self.centralwidget)
        self.textEdit_41.setObjectName(u"textEdit_41")
        self.textEdit_41.setGeometry(QRect(520, 170, 31, 31))
        self.textEdit_42 = QTextEdit(self.centralwidget)
        self.textEdit_42.setObjectName(u"textEdit_42")
        self.textEdit_42.setGeometry(QRect(460, 140, 31, 31))
        self.textEdit_43 = QTextEdit(self.centralwidget)
        self.textEdit_43.setObjectName(u"textEdit_43")
        self.textEdit_43.setGeometry(QRect(520, 140, 31, 31))
        self.textEdit_44 = QTextEdit(self.centralwidget)
        self.textEdit_44.setObjectName(u"textEdit_44")
        self.textEdit_44.setGeometry(QRect(460, 170, 31, 31))
        self.textEdit_45 = QTextEdit(self.centralwidget)
        self.textEdit_45.setObjectName(u"textEdit_45")
        self.textEdit_45.setGeometry(QRect(550, 140, 31, 31))
        self.textEdit_46 = QTextEdit(self.centralwidget)
        self.textEdit_46.setObjectName(u"textEdit_46")
        self.textEdit_46.setGeometry(QRect(490, 140, 31, 31))
        self.textEdit_47 = QTextEdit(self.centralwidget)
        self.textEdit_47.setObjectName(u"textEdit_47")
        self.textEdit_47.setGeometry(QRect(490, 170, 31, 31))
        self.textEdit_48 = QTextEdit(self.centralwidget)
        self.textEdit_48.setObjectName(u"textEdit_48")
        self.textEdit_48.setGeometry(QRect(550, 170, 31, 31))
        self.textEdit_49 = QTextEdit(self.centralwidget)
        self.textEdit_49.setObjectName(u"textEdit_49")
        self.textEdit_49.setGeometry(QRect(400, 290, 31, 31))
        self.textEdit_50 = QTextEdit(self.centralwidget)
        self.textEdit_50.setObjectName(u"textEdit_50")
        self.textEdit_50.setGeometry(QRect(310, 230, 31, 31))
        self.textEdit_51 = QTextEdit(self.centralwidget)
        self.textEdit_51.setObjectName(u"textEdit_51")
        self.textEdit_51.setGeometry(QRect(250, 260, 31, 31))
        self.textEdit_52 = QTextEdit(self.centralwidget)
        self.textEdit_52.setObjectName(u"textEdit_52")
        self.textEdit_52.setGeometry(QRect(550, 260, 31, 31))
        self.textEdit_53 = QTextEdit(self.centralwidget)
        self.textEdit_53.setObjectName(u"textEdit_53")
        self.textEdit_53.setGeometry(QRect(220, 200, 31, 31))
        self.textEdit_54 = QTextEdit(self.centralwidget)
        self.textEdit_54.setObjectName(u"textEdit_54")
        self.textEdit_54.setGeometry(QRect(370, 290, 31, 31))
        self.textEdit_55 = QTextEdit(self.centralwidget)
        self.textEdit_55.setObjectName(u"textEdit_55")
        self.textEdit_55.setGeometry(QRect(400, 260, 31, 31))
        self.textEdit_56 = QTextEdit(self.centralwidget)
        self.textEdit_56.setObjectName(u"textEdit_56")
        self.textEdit_56.setGeometry(QRect(460, 230, 31, 31))
        self.textEdit_57 = QTextEdit(self.centralwidget)
        self.textEdit_57.setObjectName(u"textEdit_57")
        self.textEdit_57.setGeometry(QRect(280, 200, 31, 31))
        self.textEdit_58 = QTextEdit(self.centralwidget)
        self.textEdit_58.setObjectName(u"textEdit_58")
        self.textEdit_58.setGeometry(QRect(460, 260, 31, 31))
        self.textEdit_59 = QTextEdit(self.centralwidget)
        self.textEdit_59.setObjectName(u"textEdit_59")
        self.textEdit_59.setGeometry(QRect(370, 260, 31, 31))
        self.textEdit_60 = QTextEdit(self.centralwidget)
        self.textEdit_60.setObjectName(u"textEdit_60")
        self.textEdit_60.setGeometry(QRect(340, 260, 31, 31))
        self.textEdit_61 = QTextEdit(self.centralwidget)
        self.textEdit_61.setObjectName(u"textEdit_61")
        self.textEdit_61.setGeometry(QRect(370, 230, 31, 31))
        self.textEdit_62 = QTextEdit(self.centralwidget)
        self.textEdit_62.setObjectName(u"textEdit_62")
        self.textEdit_62.setGeometry(QRect(250, 290, 31, 31))
        self.textEdit_63 = QTextEdit(self.centralwidget)
        self.textEdit_63.setObjectName(u"textEdit_63")
        self.textEdit_63.setGeometry(QRect(460, 200, 31, 31))
        self.textEdit_64 = QTextEdit(self.centralwidget)
        self.textEdit_64.setObjectName(u"textEdit_64")
        self.textEdit_64.setGeometry(QRect(280, 290, 31, 31))
        self.textEdit_65 = QTextEdit(self.centralwidget)
        self.textEdit_65.setObjectName(u"textEdit_65")
        self.textEdit_65.setGeometry(QRect(400, 200, 31, 31))
        self.textEdit_66 = QTextEdit(self.centralwidget)
        self.textEdit_66.setObjectName(u"textEdit_66")
        self.textEdit_66.setGeometry(QRect(490, 230, 31, 31))
        self.textEdit_67 = QTextEdit(self.centralwidget)
        self.textEdit_67.setObjectName(u"textEdit_67")
        self.textEdit_67.setGeometry(QRect(490, 200, 31, 31))
        self.textEdit_68 = QTextEdit(self.centralwidget)
        self.textEdit_68.setObjectName(u"textEdit_68")
        self.textEdit_68.setGeometry(QRect(280, 230, 31, 31))
        self.textEdit_69 = QTextEdit(self.centralwidget)
        self.textEdit_69.setObjectName(u"textEdit_69")
        self.textEdit_69.setGeometry(QRect(490, 260, 31, 31))
        self.textEdit_70 = QTextEdit(self.centralwidget)
        self.textEdit_70.setObjectName(u"textEdit_70")
        self.textEdit_70.setGeometry(QRect(310, 260, 31, 31))
        self.textEdit_71 = QTextEdit(self.centralwidget)
        self.textEdit_71.setObjectName(u"textEdit_71")
        self.textEdit_71.setGeometry(QRect(430, 260, 31, 31))
        self.textEdit_72 = QTextEdit(self.centralwidget)
        self.textEdit_72.setObjectName(u"textEdit_72")
        self.textEdit_72.setGeometry(QRect(550, 230, 31, 31))
        self.textEdit_73 = QTextEdit(self.centralwidget)
        self.textEdit_73.setObjectName(u"textEdit_73")
        self.textEdit_73.setGeometry(QRect(220, 290, 31, 31))
        self.textEdit_74 = QTextEdit(self.centralwidget)
        self.textEdit_74.setObjectName(u"textEdit_74")
        self.textEdit_74.setGeometry(QRect(400, 230, 31, 31))
        self.textEdit_75 = QTextEdit(self.centralwidget)
        self.textEdit_75.setObjectName(u"textEdit_75")
        self.textEdit_75.setGeometry(QRect(220, 260, 31, 31))
        self.textEdit_76 = QTextEdit(self.centralwidget)
        self.textEdit_76.setObjectName(u"textEdit_76")
        self.textEdit_76.setGeometry(QRect(430, 290, 31, 31))
        self.textEdit_77 = QTextEdit(self.centralwidget)
        self.textEdit_77.setObjectName(u"textEdit_77")
        self.textEdit_77.setGeometry(QRect(550, 290, 31, 31))
        self.textEdit_78 = QTextEdit(self.centralwidget)
        self.textEdit_78.setObjectName(u"textEdit_78")
        self.textEdit_78.setGeometry(QRect(520, 290, 31, 31))
        self.textEdit_79 = QTextEdit(self.centralwidget)
        self.textEdit_79.setObjectName(u"textEdit_79")
        self.textEdit_79.setGeometry(QRect(250, 230, 31, 31))
        self.textEdit_80 = QTextEdit(self.centralwidget)
        self.textEdit_80.setObjectName(u"textEdit_80")
        self.textEdit_80.setGeometry(QRect(250, 200, 31, 31))
        self.textEdit_81 = QTextEdit(self.centralwidget)
        self.textEdit_81.setObjectName(u"textEdit_81")
        self.textEdit_81.setGeometry(QRect(310, 200, 31, 31))
        self.textEdit_82 = QTextEdit(self.centralwidget)
        self.textEdit_82.setObjectName(u"textEdit_82")
        self.textEdit_82.setGeometry(QRect(430, 200, 31, 31))
        self.textEdit_83 = QTextEdit(self.centralwidget)
        self.textEdit_83.setObjectName(u"textEdit_83")
        self.textEdit_83.setGeometry(QRect(280, 260, 31, 31))
        self.textEdit_84 = QTextEdit(self.centralwidget)
        self.textEdit_84.setObjectName(u"textEdit_84")
        self.textEdit_84.setGeometry(QRect(520, 230, 31, 31))
        self.textEdit_85 = QTextEdit(self.centralwidget)
        self.textEdit_85.setObjectName(u"textEdit_85")
        self.textEdit_85.setGeometry(QRect(490, 290, 31, 31))
        self.textEdit_86 = QTextEdit(self.centralwidget)
        self.textEdit_86.setObjectName(u"textEdit_86")
        self.textEdit_86.setGeometry(QRect(430, 230, 31, 31))
        self.textEdit_87 = QTextEdit(self.centralwidget)
        self.textEdit_87.setObjectName(u"textEdit_87")
        self.textEdit_87.setGeometry(QRect(520, 200, 31, 31))
        self.textEdit_88 = QTextEdit(self.centralwidget)
        self.textEdit_88.setObjectName(u"textEdit_88")
        self.textEdit_88.setGeometry(QRect(370, 200, 31, 31))
        self.textEdit_89 = QTextEdit(self.centralwidget)
        self.textEdit_89.setObjectName(u"textEdit_89")
        self.textEdit_89.setGeometry(QRect(220, 230, 31, 31))
        self.textEdit_90 = QTextEdit(self.centralwidget)
        self.textEdit_90.setObjectName(u"textEdit_90")
        self.textEdit_90.setGeometry(QRect(520, 260, 31, 31))
        self.textEdit_91 = QTextEdit(self.centralwidget)
        self.textEdit_91.setObjectName(u"textEdit_91")
        self.textEdit_91.setGeometry(QRect(460, 290, 31, 31))
        self.textEdit_92 = QTextEdit(self.centralwidget)
        self.textEdit_92.setObjectName(u"textEdit_92")
        self.textEdit_92.setGeometry(QRect(340, 230, 31, 31))
        self.textEdit_93 = QTextEdit(self.centralwidget)
        self.textEdit_93.setObjectName(u"textEdit_93")
        self.textEdit_93.setGeometry(QRect(340, 200, 31, 31))
        self.textEdit_94 = QTextEdit(self.centralwidget)
        self.textEdit_94.setObjectName(u"textEdit_94")
        self.textEdit_94.setGeometry(QRect(310, 290, 31, 31))
        self.textEdit_95 = QTextEdit(self.centralwidget)
        self.textEdit_95.setObjectName(u"textEdit_95")
        self.textEdit_95.setGeometry(QRect(340, 290, 31, 31))
        self.textEdit_96 = QTextEdit(self.centralwidget)
        self.textEdit_96.setObjectName(u"textEdit_96")
        self.textEdit_96.setGeometry(QRect(550, 200, 31, 31))
        self.textEdit_97 = QTextEdit(self.centralwidget)
        self.textEdit_97.setObjectName(u"textEdit_97")
        self.textEdit_97.setGeometry(QRect(400, 410, 31, 31))
        self.textEdit_98 = QTextEdit(self.centralwidget)
        self.textEdit_98.setObjectName(u"textEdit_98")
        self.textEdit_98.setGeometry(QRect(310, 350, 31, 31))
        self.textEdit_99 = QTextEdit(self.centralwidget)
        self.textEdit_99.setObjectName(u"textEdit_99")
        self.textEdit_99.setGeometry(QRect(250, 380, 31, 31))
        self.textEdit_100 = QTextEdit(self.centralwidget)
        self.textEdit_100.setObjectName(u"textEdit_100")
        self.textEdit_100.setGeometry(QRect(550, 380, 31, 31))
        self.textEdit_101 = QTextEdit(self.centralwidget)
        self.textEdit_101.setObjectName(u"textEdit_101")
        self.textEdit_101.setGeometry(QRect(220, 320, 31, 31))
        self.textEdit_102 = QTextEdit(self.centralwidget)
        self.textEdit_102.setObjectName(u"textEdit_102")
        self.textEdit_102.setGeometry(QRect(370, 410, 31, 31))
        self.textEdit_103 = QTextEdit(self.centralwidget)
        self.textEdit_103.setObjectName(u"textEdit_103")
        self.textEdit_103.setGeometry(QRect(400, 380, 31, 31))
        self.textEdit_104 = QTextEdit(self.centralwidget)
        self.textEdit_104.setObjectName(u"textEdit_104")
        self.textEdit_104.setGeometry(QRect(460, 350, 31, 31))
        self.textEdit_105 = QTextEdit(self.centralwidget)
        self.textEdit_105.setObjectName(u"textEdit_105")
        self.textEdit_105.setGeometry(QRect(280, 320, 31, 31))
        self.textEdit_106 = QTextEdit(self.centralwidget)
        self.textEdit_106.setObjectName(u"textEdit_106")
        self.textEdit_106.setGeometry(QRect(460, 380, 31, 31))
        self.textEdit_107 = QTextEdit(self.centralwidget)
        self.textEdit_107.setObjectName(u"textEdit_107")
        self.textEdit_107.setGeometry(QRect(370, 380, 31, 31))
        self.textEdit_108 = QTextEdit(self.centralwidget)
        self.textEdit_108.setObjectName(u"textEdit_108")
        self.textEdit_108.setGeometry(QRect(340, 380, 31, 31))
        self.textEdit_109 = QTextEdit(self.centralwidget)
        self.textEdit_109.setObjectName(u"textEdit_109")
        self.textEdit_109.setGeometry(QRect(370, 350, 31, 31))
        self.textEdit_110 = QTextEdit(self.centralwidget)
        self.textEdit_110.setObjectName(u"textEdit_110")
        self.textEdit_110.setGeometry(QRect(250, 410, 31, 31))
        self.textEdit_111 = QTextEdit(self.centralwidget)
        self.textEdit_111.setObjectName(u"textEdit_111")
        self.textEdit_111.setGeometry(QRect(460, 320, 31, 31))
        self.textEdit_112 = QTextEdit(self.centralwidget)
        self.textEdit_112.setObjectName(u"textEdit_112")
        self.textEdit_112.setGeometry(QRect(280, 410, 31, 31))
        self.textEdit_113 = QTextEdit(self.centralwidget)
        self.textEdit_113.setObjectName(u"textEdit_113")
        self.textEdit_113.setGeometry(QRect(400, 320, 31, 31))
        self.textEdit_114 = QTextEdit(self.centralwidget)
        self.textEdit_114.setObjectName(u"textEdit_114")
        self.textEdit_114.setGeometry(QRect(490, 350, 31, 31))
        self.textEdit_115 = QTextEdit(self.centralwidget)
        self.textEdit_115.setObjectName(u"textEdit_115")
        self.textEdit_115.setGeometry(QRect(490, 320, 31, 31))
        self.textEdit_116 = QTextEdit(self.centralwidget)
        self.textEdit_116.setObjectName(u"textEdit_116")
        self.textEdit_116.setGeometry(QRect(280, 350, 31, 31))
        self.textEdit_117 = QTextEdit(self.centralwidget)
        self.textEdit_117.setObjectName(u"textEdit_117")
        self.textEdit_117.setGeometry(QRect(490, 380, 31, 31))
        self.textEdit_118 = QTextEdit(self.centralwidget)
        self.textEdit_118.setObjectName(u"textEdit_118")
        self.textEdit_118.setGeometry(QRect(310, 380, 31, 31))
        self.textEdit_119 = QTextEdit(self.centralwidget)
        self.textEdit_119.setObjectName(u"textEdit_119")
        self.textEdit_119.setGeometry(QRect(430, 380, 31, 31))
        self.textEdit_120 = QTextEdit(self.centralwidget)
        self.textEdit_120.setObjectName(u"textEdit_120")
        self.textEdit_120.setGeometry(QRect(550, 350, 31, 31))
        self.textEdit_121 = QTextEdit(self.centralwidget)
        self.textEdit_121.setObjectName(u"textEdit_121")
        self.textEdit_121.setGeometry(QRect(220, 410, 31, 31))
        self.textEdit_122 = QTextEdit(self.centralwidget)
        self.textEdit_122.setObjectName(u"textEdit_122")
        self.textEdit_122.setGeometry(QRect(400, 350, 31, 31))
        self.textEdit_123 = QTextEdit(self.centralwidget)
        self.textEdit_123.setObjectName(u"textEdit_123")
        self.textEdit_123.setGeometry(QRect(220, 380, 31, 31))
        self.textEdit_124 = QTextEdit(self.centralwidget)
        self.textEdit_124.setObjectName(u"textEdit_124")
        self.textEdit_124.setGeometry(QRect(430, 410, 31, 31))
        self.textEdit_125 = QTextEdit(self.centralwidget)
        self.textEdit_125.setObjectName(u"textEdit_125")
        self.textEdit_125.setGeometry(QRect(550, 410, 31, 31))
        self.textEdit_126 = QTextEdit(self.centralwidget)
        self.textEdit_126.setObjectName(u"textEdit_126")
        self.textEdit_126.setGeometry(QRect(520, 410, 31, 31))
        self.textEdit_127 = QTextEdit(self.centralwidget)
        self.textEdit_127.setObjectName(u"textEdit_127")
        self.textEdit_127.setGeometry(QRect(250, 350, 31, 31))
        self.textEdit_128 = QTextEdit(self.centralwidget)
        self.textEdit_128.setObjectName(u"textEdit_128")
        self.textEdit_128.setGeometry(QRect(250, 320, 31, 31))
        self.textEdit_129 = QTextEdit(self.centralwidget)
        self.textEdit_129.setObjectName(u"textEdit_129")
        self.textEdit_129.setGeometry(QRect(310, 320, 31, 31))
        self.textEdit_130 = QTextEdit(self.centralwidget)
        self.textEdit_130.setObjectName(u"textEdit_130")
        self.textEdit_130.setGeometry(QRect(430, 320, 31, 31))
        self.textEdit_131 = QTextEdit(self.centralwidget)
        self.textEdit_131.setObjectName(u"textEdit_131")
        self.textEdit_131.setGeometry(QRect(280, 380, 31, 31))
        self.textEdit_132 = QTextEdit(self.centralwidget)
        self.textEdit_132.setObjectName(u"textEdit_132")
        self.textEdit_132.setGeometry(QRect(520, 350, 31, 31))
        self.textEdit_133 = QTextEdit(self.centralwidget)
        self.textEdit_133.setObjectName(u"textEdit_133")
        self.textEdit_133.setGeometry(QRect(490, 410, 31, 31))
        self.textEdit_134 = QTextEdit(self.centralwidget)
        self.textEdit_134.setObjectName(u"textEdit_134")
        self.textEdit_134.setGeometry(QRect(430, 350, 31, 31))
        self.textEdit_135 = QTextEdit(self.centralwidget)
        self.textEdit_135.setObjectName(u"textEdit_135")
        self.textEdit_135.setGeometry(QRect(520, 320, 31, 31))
        self.textEdit_136 = QTextEdit(self.centralwidget)
        self.textEdit_136.setObjectName(u"textEdit_136")
        self.textEdit_136.setGeometry(QRect(370, 320, 31, 31))
        self.textEdit_137 = QTextEdit(self.centralwidget)
        self.textEdit_137.setObjectName(u"textEdit_137")
        self.textEdit_137.setGeometry(QRect(220, 350, 31, 31))
        self.textEdit_138 = QTextEdit(self.centralwidget)
        self.textEdit_138.setObjectName(u"textEdit_138")
        self.textEdit_138.setGeometry(QRect(520, 380, 31, 31))
        self.textEdit_139 = QTextEdit(self.centralwidget)
        self.textEdit_139.setObjectName(u"textEdit_139")
        self.textEdit_139.setGeometry(QRect(460, 410, 31, 31))
        self.textEdit_140 = QTextEdit(self.centralwidget)
        self.textEdit_140.setObjectName(u"textEdit_140")
        self.textEdit_140.setGeometry(QRect(340, 350, 31, 31))
        self.textEdit_141 = QTextEdit(self.centralwidget)
        self.textEdit_141.setObjectName(u"textEdit_141")
        self.textEdit_141.setGeometry(QRect(340, 320, 31, 31))
        self.textEdit_142 = QTextEdit(self.centralwidget)
        self.textEdit_142.setObjectName(u"textEdit_142")
        self.textEdit_142.setGeometry(QRect(310, 410, 31, 31))
        self.textEdit_143 = QTextEdit(self.centralwidget)
        self.textEdit_143.setObjectName(u"textEdit_143")
        self.textEdit_143.setGeometry(QRect(340, 410, 31, 31))
        self.textEdit_144 = QTextEdit(self.centralwidget)
        self.textEdit_144.setObjectName(u"textEdit_144")
        self.textEdit_144.setGeometry(QRect(550, 320, 31, 31))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.b_Start.setText(QCoreApplication.translate("MainWindow", u"J\u00e1t\u00e9k Ind\u00edt\u00e1sa", None))
        self.b_Exit.setText(QCoreApplication.translate("MainWindow", u"Kil\u00e9p\u00e9s", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Add meg a neved!", None))
        self.in_Name.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">N\u00e9v</p></body></html>", None))
    # retranslateUi

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())